[package]
name = "life-agent-for-windows"
version = "0.1.0"
edition = "2021"

[dependencies]
rdev = "*"
sysinfo = "^0"
tokio = { version = "^1.19", features = ["full"] }

[target.'cfg(windows)'.dependencies.windows]
version = "^0.58"
features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_Threading",
  "Win32_System_SystemInformation",
  "Win32_UI_WindowsAndMessaging",
  "Win32_UI_Input_KeyboardAndMouse",
]

[target.'cfg(target_os = "linux")'.dependencies]
x11rb = "0.11.1"
user-idle = "0.6.0"
